image_size: 32
number_of_classes: 100

train:
  _target_: data_module.CIFAR100Dataset
  dataset_path: data/DP/CIFAR-100/cifar-100-python/train

test:
  _target_: data_module.CIFAR100Dataset
  dataset_path: data/DP/CIFAR-100/cifar-100-python/test