defaults:
    - _self_
    - datasets: ImageNet # ImageNet # CIFAR-10 # Covid19-256 # CIFAR-100 # CIFAR-10 # Covid19-256 # SVHN

config:
    model_info:
        feature_extractor: resnet50.a1_in1k # resnet32_cifar # resnet20_cifar # resnet44_cifar # resnet56_cifar # resnet32ts.ra2_in1k # resnet18.a1_in1k # svhn # cifar10
        hue_augmentator: hue_augmentator_256 # resnet32ts.ra2_in1k # resnet18.a1_in1k # svhn # cifar10 
    train_info:
        project: DP2
        name: ResNet50.a1_in1kImageNetOurAugment # ResNet18.a1_in1kCovid19NewUNet # ResNet18.a1_in1kCIFAR10NoAugment # ResNet18.a1_in1kCovid19NoAugment # Resnet18CovidBoundedFeedbackOn
        version: 1
        epochs: 60 # 20
        trials: 50 # 10
        device: cuda
        primary_learning_rate:
            min_value: 0.0001
            max_value: 0.01
        affine_augmentator_learning_rate:
            min_value: 0.001
            max_value: 0.01
        hue_augmentator_learning_rate:
            min_value: 0.001
            max_value: 0.01
        hue_l2_weight:
            min_value: 2.0 # viac
            max_value: 7.0
        affine_l2_weight:
            min_value: 2.0
            max_value: 7.0
        ssim_weight:
            min_value: 1.0 # menej
            max_value: 2.0
        rotation_weight:
            min_value: 1.0
            max_value: 1.5
        translation_weight:
            min_value: 0.05
            max_value: 0.1
        scaling_weight:
            min_value: 1.0
            max_value: 1.25
        scaling_bound:
            min_value: 0.909090909
            max_value: 1.1
        translation_bound:
            min_value: -0.25
            max_value: 0.25
        rotation_bound:
            min_value: -0.175 # +- 10 degrees
            max_value: 0.175
        padding_mode: zeros
        primary_weight_decay: 0
        batch_size: 64 # 512
        num_workers: 1 # 2
        to_be_augmented: True
        to_save_augmented: False
        wandb: True
